os:
- osx
osx_image: xcode7.2
language: generic
env:
  global:
  - 'DEVELOPER_NAME="Mac Distribution: Deco Desktop Production (M5Y2HY4UM2)"'
  - PROFILE_NAME="Deco_Desktop_Production"
  - SIGN_DECO_PACKAGE="true"
  - secure: "KzIJWOowlXk3lj8NH43gVQsIXq0saqULLU2vHLLDrIceA7n0Ntj/yQuG3FNW/0JXEXMb95OnMkckeSTuXV5bcsbyQ+SwIT/xTlS6VP5AB/n3G7iNkfVQduK/L0mAiIRLLDflAKp7xwx+CojLQPP16LiQJ55OV9HA5NVAQvp3M9krRHcHkYBAdhD1M3m1ZFf87DEnEqn2wUtrK+6SB5zUcWzZfS1HYaZrfvblTwQDEOXKU86N60qB8vMww0K6dDVrkIoltWpgOMU9LkS9I+nNeyIutBSqOJckyDLoFNY64KuxR+q+VH09g/0T6vPczxuMaS0L+qLLtyQ1UbGGEUq33dy8PQ8bVEs613GYxEB0rDgRua3ErwIf9Y5nxvQmfCjQ0mX2P0ZIsYqLc2LmEhMNfphnUYx8WLt9YBukX9ZMM1asBls7rOZ5GT20AdwPgoksc/SVZhBvO+OqGmIjyERV0IDPw1nn21q//3Ks6Tq+55zVppyngC60Kl8kw6xahjcPxhVr5amnPmjUQMHvBqeJrC9rD5Nnmxj+AkLGCEFzkx85KTM3rq7JL6HGbuq8Od9ebmDDnVSNkOmmEqu6I31pDdNtbExojPKqndvdNbH3cgbtdjETUWGvZf7XCJJddVT+/dqCSAh3UVNewVsysxp0fhwOMCtR26R7QJ12pyb5NPQ="
  matrix:
  - NODE_VERSION="5.7"
before_install:
- brew update
- brew install curl
- git clone https://github.com/creationix/nvm.git /tmp/.nvm; source /tmp/.nvm/nvm.sh;
  nvm install $NODE_VERSION; nvm use --delete-prefix $NODE_VERSION;
install:
- "./build/install-dependencies.sh"
script:
- "./build/run-pack.sh"
cache:
  bundler: true
  directories:
  - shared/node_modules
  - desktop/node_modules
  - web/node_modules
deploy:
- provider: s3
  access_key_id: AKIAJS2NLE6DTHZPCBNQ
  secret_access_key:
    secure: "a6KSzyTF33P6rZsyMR/B98E92P76y0DqxaoR/ocy4a2b6uL5XpPYh606QIxbLe1pdpcLfGm+L9yR0uAy4R615xGbaaz4Loy16UNxBkaHAQ1sxmFMc2oZKnWgCK6eO5MCLBhKCqUYAFY6U+QLJ4nyGhV4RywdyCuIsRJjCBGGHorgUcQZw5nZ+n9fpEHaQqsFBrL4ilaK+VoUJFYVruj8ggRHzgJ7/q5XsKKqKcFuMJzLOzLgQML0Wk3d4j20D8d+dZ2mGxtaULXNjGdhttFFIlXgn2VrLQszBvEqaFaZF7X6HZ2DZfLG2TchHhpHLyXe4uf9Tnn0L+xqvsMjGS4FLfAaCPyKBkLHc315lymzYLDDRJbD4vfB0QMoK/vV/+3/kd2kDQzG/ponSoSPHZU4TipAa1BwzMp041hYpu/ziH6SRyEAGAA8LDxpVUXmTP9Y7QC5Rze0/R4zdwqr1Pyi0qr6MI9jtHIryouNIomeSXy4LiZvBWYivyrJB/eQX1BT/w/dkDpleL9DJx7y0sWP5KJpIf8F7Tgv7quNbRzHobi7pJeuC1QUqCr1Nte74GAOwg9QP/g4LG80Rhvw4Rcto67VOg5wT7FRJfip1Eli4IGev3YZWmeoy4gupOWfJai15pIQ/hU7v2ExioA9jjFdl69qU1ZVVFBzwyMYteuV75I="
  bucket: decopkgs
  skip_cleanup: true
  local_dir: dist
  on:
    branch: release
- provider: s3
  access_key_id: AKIAJS2NLE6DTHZPCBNQ
  secret_access_key:
    secure: "a6KSzyTF33P6rZsyMR/B98E92P76y0DqxaoR/ocy4a2b6uL5XpPYh606QIxbLe1pdpcLfGm+L9yR0uAy4R615xGbaaz4Loy16UNxBkaHAQ1sxmFMc2oZKnWgCK6eO5MCLBhKCqUYAFY6U+QLJ4nyGhV4RywdyCuIsRJjCBGGHorgUcQZw5nZ+n9fpEHaQqsFBrL4ilaK+VoUJFYVruj8ggRHzgJ7/q5XsKKqKcFuMJzLOzLgQML0Wk3d4j20D8d+dZ2mGxtaULXNjGdhttFFIlXgn2VrLQszBvEqaFaZF7X6HZ2DZfLG2TchHhpHLyXe4uf9Tnn0L+xqvsMjGS4FLfAaCPyKBkLHc315lymzYLDDRJbD4vfB0QMoK/vV/+3/kd2kDQzG/ponSoSPHZU4TipAa1BwzMp041hYpu/ziH6SRyEAGAA8LDxpVUXmTP9Y7QC5Rze0/R4zdwqr1Pyi0qr6MI9jtHIryouNIomeSXy4LiZvBWYivyrJB/eQX1BT/w/dkDpleL9DJx7y0sWP5KJpIf8F7Tgv7quNbRzHobi7pJeuC1QUqCr1Nte74GAOwg9QP/g4LG80Rhvw4Rcto67VOg5wT7FRJfip1Eli4IGev3YZWmeoy4gupOWfJai15pIQ/hU7v2ExioA9jjFdl69qU1ZVVFBzwyMYteuV75I="
  bucket: decopkgs-staging
  skip_cleanup: true
  local_dir: dist
  on:
    branch: staging
- provider: s3
  access_key_id: AKIAJS2NLE6DTHZPCBNQ
  secret_access_key:
    secure: "a6KSzyTF33P6rZsyMR/B98E92P76y0DqxaoR/ocy4a2b6uL5XpPYh606QIxbLe1pdpcLfGm+L9yR0uAy4R615xGbaaz4Loy16UNxBkaHAQ1sxmFMc2oZKnWgCK6eO5MCLBhKCqUYAFY6U+QLJ4nyGhV4RywdyCuIsRJjCBGGHorgUcQZw5nZ+n9fpEHaQqsFBrL4ilaK+VoUJFYVruj8ggRHzgJ7/q5XsKKqKcFuMJzLOzLgQML0Wk3d4j20D8d+dZ2mGxtaULXNjGdhttFFIlXgn2VrLQszBvEqaFaZF7X6HZ2DZfLG2TchHhpHLyXe4uf9Tnn0L+xqvsMjGS4FLfAaCPyKBkLHc315lymzYLDDRJbD4vfB0QMoK/vV/+3/kd2kDQzG/ponSoSPHZU4TipAa1BwzMp041hYpu/ziH6SRyEAGAA8LDxpVUXmTP9Y7QC5Rze0/R4zdwqr1Pyi0qr6MI9jtHIryouNIomeSXy4LiZvBWYivyrJB/eQX1BT/w/dkDpleL9DJx7y0sWP5KJpIf8F7Tgv7quNbRzHobi7pJeuC1QUqCr1Nte74GAOwg9QP/g4LG80Rhvw4Rcto67VOg5wT7FRJfip1Eli4IGev3YZWmeoy4gupOWfJai15pIQ/hU7v2ExioA9jjFdl69qU1ZVVFBzwyMYteuV75I="
  bucket: decopkgs-bleeding-edge
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
branches:
  only:
  - release
  - staging
  - master
