os:
- osx
osx_image: xcode7.2
language: generic
env:
  global:
  - 'DEVELOPER_NAME="Mac Distribution: Deco Desktop Production (M5Y2HY4UM2)"'
  - PROFILE_NAME="Deco_Desktop_Production"
  - SIGN_DECO_PACKAGE="true"
  - secure: "ZRniHrBDBBVrtQHFqIHCv8Hh2xdXh0f5QhewBGfYBXK5PJSuTcCRmLHnZnpbVLGcfrccz+5zgo3AaY6mtQxpnXxCzB+8nX7QJ779Dz276MGgMytmC6bekv3PVcVaFUcbviWarD0nzzU0uY9k5U4kj8GjsvQ4G7Y9ULJcO2fERjXhayaSsnCJxPLs66gZcdizo4fl+8Xy7qXKgZiYpTUv4rCGuDFbqzpmPRjwd0ymmBsGI4DpAWNxGUWrCOk7DV8xNW5UxQ2uCzibhjgr6AnZIxxHNteIfe4dnrFDsxHFgX12H2K/WypLuNG9D0fIiPo/c6/PCGwQJfggZC1PP+a5EjZsi7VCEehtSq5w3y4Z4JKOaTmzXZ853Tl485e7GmYE2mh0mwVY6Xw1Cwa/O/zWPtU0ttO6IgkboSXNQ6/XOCvZcYGClSKHPaW/MEDHMbv+HNJuponKEo61qYXvHDzJ0oM+hviPM7Ok49tssgWp2YGB87Um7V8ZJjezTJacwjauOb+cvjUGZ6TokSEMyKiVGyrmvqN4WqOlnkWL0wkOWopdFnGu9JvLR16ODc6cO/5tVGLogp5HAp4myfZa6Jmv1jp1mCCTWx0zjwQlokxXnytPZrH763n6qaZr6vb28XzFZTY3fizEff4YdIAlBIcvmloNymaCbj1cGBgYBo+WfsQ="  
  matrix:
  - NODE_VERSION="5.7"
before_install:
- brew update
- brew install curl
- git clone https://github.com/creationix/nvm.git /tmp/.nvm; source /tmp/.nvm/nvm.sh;
  nvm install $NODE_VERSION; nvm use --delete-prefix $NODE_VERSION;
install:
- "./build/install-dependencies.sh"
script:
- "./build/run-pack.sh"
cache:
  bundler: true
  directories:
  - shared/node_modules
  - desktop/node_modules
  - web/node_modules
deploy:
- provider: s3
  access_key_id: AKIAJETVMVT2MJZNMHCQ
  secret_access_key:
    secure: "ANmoBOs9oDwUyzXGvLOQHx56lXXWzBSsBC4IW25bPCPOII8ONtcrCr9QdWkpWc8SaKebPSunY6HO3oEAmtudKJEymVaAopwC5xMpKbvE6WEhxK86dL9BuczDLR7u1/SMDHGZrsrkJwc4TD9sVwydlg33NIH8xYb8fGTZy6bXS8tAe7L1FQeCiQYxb0P+O7q7ywfkgbRVHc0yUmrIZzsbQovEf7jITXeMbBwAwqPtWUeY5iYVCi+W9WYAgcu0WnJ+GWkaGrucb8aalJD1o5RfSodXBUa7GKOz4JUIoDtTw/3vD4/BIKeVKd1hDRRaLbQBefLUavpvEgh61k33wfByKW+Seq48ylHm7bZ/9dNbIO6jMuV8FNkowZPjf2lINGrtW44mTQjjdpkLpPZT8EhSDWJlXC+UkObQPy9IfDhgZdDZNbC93UUj3iWWDy4x71GqnGdpcuXIPPCAQiIydcYnJN1TJtQ7T0RWFZx83PnYPzqyVEctbMw1AB4ZyhjvZmL7C3v+VqfbwhWuOTmMLbmXaA0emGOlhD4Sul0+KSdF7ddzQ6Rn9LZ0YKfsjusSudg4FiTzg6aBHRkZa2uUyjkWD/9yN6SOygYHRpfIpXj0QHfvr3bwGJqhpCo0EH9gFQvJskv6c54p8A4R0L2ESf4upw2xw0H689O8SFe6GQLiJGg="
  bucket: decopkgs
  skip_cleanup: true
  local_dir: dist
  on:
    branch: release
- provider: s3
  access_key_id: AKIAJETVMVT2MJZNMHCQ
  secret_access_key:
    secure: "ANmoBOs9oDwUyzXGvLOQHx56lXXWzBSsBC4IW25bPCPOII8ONtcrCr9QdWkpWc8SaKebPSunY6HO3oEAmtudKJEymVaAopwC5xMpKbvE6WEhxK86dL9BuczDLR7u1/SMDHGZrsrkJwc4TD9sVwydlg33NIH8xYb8fGTZy6bXS8tAe7L1FQeCiQYxb0P+O7q7ywfkgbRVHc0yUmrIZzsbQovEf7jITXeMbBwAwqPtWUeY5iYVCi+W9WYAgcu0WnJ+GWkaGrucb8aalJD1o5RfSodXBUa7GKOz4JUIoDtTw/3vD4/BIKeVKd1hDRRaLbQBefLUavpvEgh61k33wfByKW+Seq48ylHm7bZ/9dNbIO6jMuV8FNkowZPjf2lINGrtW44mTQjjdpkLpPZT8EhSDWJlXC+UkObQPy9IfDhgZdDZNbC93UUj3iWWDy4x71GqnGdpcuXIPPCAQiIydcYnJN1TJtQ7T0RWFZx83PnYPzqyVEctbMw1AB4ZyhjvZmL7C3v+VqfbwhWuOTmMLbmXaA0emGOlhD4Sul0+KSdF7ddzQ6Rn9LZ0YKfsjusSudg4FiTzg6aBHRkZa2uUyjkWD/9yN6SOygYHRpfIpXj0QHfvr3bwGJqhpCo0EH9gFQvJskv6c54p8A4R0L2ESf4upw2xw0H689O8SFe6GQLiJGg="
  bucket: decopkgs-staging
  skip_cleanup: true
  local_dir: dist
  on:
    branch: staging
- provider: s3
  access_key_id: AKIAJETVMVT2MJZNMHCQ
  secret_access_key:
    secure: "ANmoBOs9oDwUyzXGvLOQHx56lXXWzBSsBC4IW25bPCPOII8ONtcrCr9QdWkpWc8SaKebPSunY6HO3oEAmtudKJEymVaAopwC5xMpKbvE6WEhxK86dL9BuczDLR7u1/SMDHGZrsrkJwc4TD9sVwydlg33NIH8xYb8fGTZy6bXS8tAe7L1FQeCiQYxb0P+O7q7ywfkgbRVHc0yUmrIZzsbQovEf7jITXeMbBwAwqPtWUeY5iYVCi+W9WYAgcu0WnJ+GWkaGrucb8aalJD1o5RfSodXBUa7GKOz4JUIoDtTw/3vD4/BIKeVKd1hDRRaLbQBefLUavpvEgh61k33wfByKW+Seq48ylHm7bZ/9dNbIO6jMuV8FNkowZPjf2lINGrtW44mTQjjdpkLpPZT8EhSDWJlXC+UkObQPy9IfDhgZdDZNbC93UUj3iWWDy4x71GqnGdpcuXIPPCAQiIydcYnJN1TJtQ7T0RWFZx83PnYPzqyVEctbMw1AB4ZyhjvZmL7C3v+VqfbwhWuOTmMLbmXaA0emGOlhD4Sul0+KSdF7ddzQ6Rn9LZ0YKfsjusSudg4FiTzg6aBHRkZa2uUyjkWD/9yN6SOygYHRpfIpXj0QHfvr3bwGJqhpCo0EH9gFQvJskv6c54p8A4R0L2ESf4upw2xw0H689O8SFe6GQLiJGg="
  bucket: decopkgs-bleeding-edge
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
branches:
  only:
  - release
  - staging
  - master
